// Data-layer pipeline. Fetches REAL overlays for the globe and writes a
// registry fragment the viewer renders from — adding a visualization is
// one entry here, no UI changes.
//
//  - Species occurrence density: GBIF map API (live), any species in SPECIES
//  - Earth observation: NASA NEO monthly datasets (vegetation, snow, fire)
//
// Output: public/textures/layer-<id>.png + src/data/layers.json
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const dest = path.join(root, 'public', 'textures')
fs.mkdirSync(dest, { recursive: true })

// ---- The catalog. Add a row, get a layer. ----
const SPECIES = [
  // Big game
  { id: 'bear', name: 'Ursus americanus', title: 'Black bear', category: 'Big game' },
  { id: 'grizzly', name: 'Ursus arctos', title: 'Grizzly / brown bear', category: 'Big game' },
  { id: 'elk', name: 'Cervus canadensis', title: 'Elk', category: 'Big game' },
  { id: 'whitetail', name: 'Odocoileus virginianus', title: 'White-tailed deer', category: 'Big game' },
  { id: 'muley', name: 'Odocoileus hemionus', title: 'Mule deer', category: 'Big game' },
  { id: 'moose', name: 'Alces alces', title: 'Moose', category: 'Big game' },
  { id: 'pronghorn', name: 'Antilocapra americana', title: 'Pronghorn', category: 'Big game' },
  { id: 'bighorn', name: 'Ovis canadensis', title: 'Bighorn sheep', category: 'Big game' },
  { id: 'mountain-goat', name: 'Oreamnos americanus', title: 'Mountain goat', category: 'Big game' },
  { id: 'caribou', name: 'Rangifer tarandus', title: 'Caribou', category: 'Big game' },
  { id: 'bison', name: 'Bison bison', title: 'Bison', category: 'Big game' },
  { id: 'mountain-lion', name: 'Puma concolor', title: 'Mountain lion', category: 'Big game' },
  { id: 'gray-wolf', name: 'Canis lupus', title: 'Gray wolf', category: 'Big game' },
  // Waterfowl
  { id: 'mallard', name: 'Anas platyrhynchos', title: 'Mallard', category: 'Waterfowl' },
  { id: 'wood-duck', name: 'Aix sponsa', title: 'Wood duck', category: 'Waterfowl' },
  { id: 'pintail', name: 'Anas acuta', title: 'Northern pintail', category: 'Waterfowl' },
  { id: 'bw-teal', name: 'Spatula discors', title: 'Blue-winged teal', category: 'Waterfowl' },
  { id: 'gw-teal', name: 'Anas carolinensis', title: 'Green-winged teal', category: 'Waterfowl' },
  { id: 'canvasback', name: 'Aythya valisineria', title: 'Canvasback', category: 'Waterfowl' },
  { id: 'redhead-duck', name: 'Aythya americana', title: 'Redhead', category: 'Waterfowl' },
  { id: 'canada-goose', name: 'Branta canadensis', title: 'Canada goose', category: 'Waterfowl' },
  { id: 'snow-goose', name: 'Anser caerulescens', title: 'Snow goose', category: 'Waterfowl' },
  { id: 'tundra-swan', name: 'Cygnus columbianus', title: 'Tundra swan', category: 'Waterfowl' },
  // Upland birds
  { id: 'grouse', name: 'Bonasa umbellus', title: 'Ruffed grouse', category: 'Upland birds' },
  { id: 'woodcock-density', name: 'Scolopax minor', title: 'American woodcock', category: 'Upland birds' },
  { id: 'turkey', name: 'Meleagris gallopavo', title: 'Wild turkey', category: 'Upland birds' },
  { id: 'bobwhite', name: 'Colinus virginianus', title: 'Northern bobwhite', category: 'Upland birds' },
  { id: 'pheasant', name: 'Phasianus colchicus', title: 'Ring-necked pheasant', category: 'Upland birds' },
  { id: 'sharptail', name: 'Tympanuchus phasianellus', title: 'Sharp-tailed grouse', category: 'Upland birds' },
  { id: 'prairie-chicken', name: 'Tympanuchus cupido', title: 'Greater prairie-chicken', category: 'Upland birds' },
  { id: 'sage-grouse', name: 'Centrocercus urophasianus', title: 'Greater sage-grouse', category: 'Upland birds' },
  { id: 'chukar', name: 'Alectoris chukar', title: 'Chukar', category: 'Upland birds' },
  { id: 'spruce-grouse', name: 'Canachites canadensis', title: 'Spruce grouse', category: 'Upland birds' },
  { id: 'dove', name: 'Zenaida macroura', title: 'Mourning dove', category: 'Upland birds' },
  // Raptors
  { id: 'bald-eagle', name: 'Haliaeetus leucocephalus', title: 'Bald eagle', category: 'Raptors' },
  { id: 'golden-eagle', name: 'Aquila chrysaetos', title: 'Golden eagle', category: 'Raptors' },
  { id: 'osprey', name: 'Pandion haliaetus', title: 'Osprey', category: 'Raptors' },
  { id: 'peregrine', name: 'Falco peregrinus', title: 'Peregrine falcon', category: 'Raptors' },
  { id: 'redtail', name: 'Buteo jamaicensis', title: 'Red-tailed hawk', category: 'Raptors' },
  { id: 'great-horned-owl', name: 'Bubo virginianus', title: 'Great horned owl', category: 'Raptors' },
  { id: 'snowy-owl', name: 'Bubo scandiacus', title: 'Snowy owl', category: 'Raptors' },
  { id: 'goshawk', name: 'Accipiter gentilis', title: 'Northern goshawk', category: 'Raptors' },
  // Fish
  { id: 'brooktrout', name: 'Salvelinus fontinalis', title: 'Brook trout', category: 'Fish' },
  { id: 'rainbow', name: 'Oncorhynchus mykiss', title: 'Rainbow trout / steelhead', category: 'Fish' },
  { id: 'brown-trout', name: 'Salmo trutta', title: 'Brown trout', category: 'Fish' },
  { id: 'cutthroat', name: 'Oncorhynchus clarkii', title: 'Cutthroat trout', category: 'Fish' },
  { id: 'lake-trout', name: 'Salvelinus namaycush', title: 'Lake trout', category: 'Fish' },
  { id: 'chinook', name: 'Oncorhynchus tshawytscha', title: 'Chinook salmon', category: 'Fish' },
  { id: 'atlantic-salmon', name: 'Salmo salar', title: 'Atlantic salmon', category: 'Fish' },
  { id: 'walleye', name: 'Sander vitreus', title: 'Walleye', category: 'Fish' },
  { id: 'smallmouth', name: 'Micropterus dolomieu', title: 'Smallmouth bass', category: 'Fish' },
  { id: 'largemouth', name: 'Micropterus salmoides', title: 'Largemouth bass', category: 'Fish' },
  { id: 'muskie', name: 'Esox masquinongy', title: 'Muskellunge', category: 'Fish' },
  { id: 'pike', name: 'Esox lucius', title: 'Northern pike', category: 'Fish' },
  { id: 'tarpon', name: 'Megalops atlanticus', title: 'Tarpon', category: 'Fish' },
  { id: 'bonefish', name: 'Albula vulpes', title: 'Bonefish', category: 'Fish' },
  // Furbearers & small game
  { id: 'snowshoe', name: 'Lepus americanus', title: 'Snowshoe hare', category: 'Furbearers & small game' },
  { id: 'cottontail', name: 'Sylvilagus floridanus', title: 'Eastern cottontail', category: 'Furbearers & small game' },
  { id: 'red-fox', name: 'Vulpes vulpes', title: 'Red fox', category: 'Furbearers & small game' },
  { id: 'coyote', name: 'Canis latrans', title: 'Coyote', category: 'Furbearers & small game' },
  { id: 'bobcat', name: 'Lynx rufus', title: 'Bobcat', category: 'Furbearers & small game' },
  { id: 'lynx', name: 'Lynx canadensis', title: 'Canada lynx', category: 'Furbearers & small game' },
  { id: 'fisher', name: 'Pekania pennanti', title: 'Fisher', category: 'Furbearers & small game' },
  { id: 'marten', name: 'Martes americana', title: 'American marten', category: 'Furbearers & small game' },
  { id: 'otter', name: 'Lontra canadensis', title: 'River otter', category: 'Furbearers & small game' },
  { id: 'beaver', name: 'Castor canadensis', title: 'Beaver', category: 'Furbearers & small game' },
  { id: 'wolverine', name: 'Gulo gulo', title: 'Wolverine', category: 'Furbearers & small game' },
  // Marine
  { id: 'gray-whale', name: 'Eschrichtius robustus', title: 'Gray whale', category: 'Ocean giants' },
  { id: 'humpback', name: 'Megaptera novaeangliae', title: 'Humpback whale', category: 'Ocean giants' },
  { id: 'orca', name: 'Orcinus orca', title: 'Orca', category: 'Ocean giants' },
  { id: 'sea-otter', name: 'Enhydra lutris', title: 'Sea otter', category: 'Ocean giants' },
  // Reptiles & amphibians
  { id: 'snapper', name: 'Chelydra serpentina', title: 'Snapping turtle', category: 'Reptiles & amphibians' },
  { id: 'timber-rattler', name: 'Crotalus horridus', title: 'Timber rattlesnake', category: 'Reptiles & amphibians' },
  { id: 'gator', name: 'Alligator mississippiensis', title: 'American alligator', category: 'Reptiles & amphibians' },
  { id: 'wood-frog', name: 'Lithobates sylvaticus', title: 'Wood frog', category: 'Reptiles & amphibians' },
  // Birds & icons
  { id: 'loon', name: 'Gavia immer', title: 'Common loon', category: 'Birds & icons' },
  { id: 'sandhill', name: 'Antigone canadensis', title: 'Sandhill crane', category: 'Birds & icons' },
  { id: 'whooping-crane', name: 'Grus americana', title: 'Whooping crane', category: 'Birds & icons' },
  { id: 'pileated', name: 'Dryocopus pileatus', title: 'Pileated woodpecker', category: 'Birds & icons' },
  { id: 'hummingbird', name: 'Archilochus colubris', title: 'Ruby-throated hummingbird', category: 'Birds & icons' },
  { id: 'monarch', name: 'Danaus plexippus', title: 'Monarch butterfly', category: 'Birds & icons' },
  // Historical
  { id: 'passenger-pigeon-records', name: 'Ectopistes migratorius', title: 'Passenger pigeon (museum records)', category: 'Historical' },
  // ---- Worldwide expansion ----
  // Bears of the world (with black + grizzly above, all eight)
  { id: "polar-bear", name: "Ursus maritimus", title: "Polar bear", category: "Bears of the world" },
  { id: "sun-bear", name: "Helarctos malayanus", title: "Sun bear", category: "Bears of the world" },
  { id: "sloth-bear", name: "Melursus ursinus", title: "Sloth bear", category: "Bears of the world" },
  { id: "spectacled-bear", name: "Tremarctos ornatus", title: "Spectacled bear", category: "Bears of the world" },
  { id: "giant-panda", name: "Ailuropoda melanoleuca", title: "Giant panda", category: "Bears of the world" },
  { id: "asiatic-black-bear", name: "Ursus thibetanus", title: "Asiatic black bear", category: "Bears of the world" },
  // Africa
  { id: "lion", name: "Panthera leo", title: "Lion", category: "Africa" },
  { id: "leopard", name: "Panthera pardus", title: "Leopard", category: "Africa" },
  { id: "cheetah", name: "Acinonyx jubatus", title: "Cheetah", category: "Africa" },
  { id: "savanna-elephant", name: "Loxodonta africana", title: "African savanna elephant", category: "Africa" },
  { id: "forest-elephant", name: "Loxodonta cyclotis", title: "African forest elephant", category: "Africa" },
  { id: "white-rhino", name: "Ceratotherium simum", title: "White rhinoceros", category: "Africa" },
  { id: "black-rhino", name: "Diceros bicornis", title: "Black rhinoceros", category: "Africa" },
  { id: "hippo", name: "Hippopotamus amphibius", title: "Hippopotamus", category: "Africa" },
  { id: "cape-buffalo", name: "Syncerus caffer", title: "Cape buffalo", category: "Africa" },
  { id: "giraffe", name: "Giraffa camelopardalis", title: "Giraffe", category: "Africa" },
  { id: "plains-zebra", name: "Equus quagga", title: "Plains zebra", category: "Africa" },
  { id: "grevys-zebra", name: "Equus grevyi", title: "Grevy's zebra", category: "Africa" },
  { id: "wildebeest", name: "Connochaetes taurinus", title: "Blue wildebeest", category: "Africa" },
  { id: "impala", name: "Aepyceros melampus", title: "Impala", category: "Africa" },
  { id: "kudu", name: "Tragelaphus strepsiceros", title: "Greater kudu", category: "Africa" },
  { id: "eland", name: "Taurotragus oryx", title: "Common eland", category: "Africa" },
  { id: "sable", name: "Hippotragus niger", title: "Sable antelope", category: "Africa" },
  { id: "gemsbok", name: "Oryx gazella", title: "Gemsbok", category: "Africa" },
  { id: "springbok", name: "Antidorcas marsupialis", title: "Springbok", category: "Africa" },
  { id: "hartebeest", name: "Alcelaphus buselaphus", title: "Hartebeest", category: "Africa" },
  { id: "thomsons-gazelle", name: "Eudorcas thomsonii", title: "Thomson's gazelle", category: "Africa" },
  { id: "warthog", name: "Phacochoerus africanus", title: "Warthog", category: "Africa" },
  { id: "wild-dog", name: "Lycaon pictus", title: "African wild dog", category: "Africa" },
  { id: "spotted-hyena", name: "Crocuta crocuta", title: "Spotted hyena", category: "Africa" },
  { id: "serval", name: "Leptailurus serval", title: "Serval", category: "Africa" },
  { id: "caracal", name: "Caracal caracal", title: "Caracal", category: "Africa" },
  { id: "western-gorilla", name: "Gorilla gorilla", title: "Western gorilla", category: "Africa" },
  { id: "eastern-gorilla", name: "Gorilla beringei", title: "Eastern gorilla", category: "Africa" },
  { id: "chimpanzee", name: "Pan troglodytes", title: "Chimpanzee", category: "Africa" },
  { id: "bonobo", name: "Pan paniscus", title: "Bonobo", category: "Africa" },
  { id: "mandrill", name: "Mandrillus sphinx", title: "Mandrill", category: "Africa" },
  { id: "chacma-baboon", name: "Papio ursinus", title: "Chacma baboon", category: "Africa" },
  { id: "ring-tailed-lemur", name: "Lemur catta", title: "Ring-tailed lemur", category: "Africa" },
  { id: "aye-aye", name: "Daubentonia madagascariensis", title: "Aye-aye", category: "Africa" },
  { id: "fossa", name: "Cryptoprocta ferox", title: "Fossa", category: "Africa" },
  { id: "okapi", name: "Okapia johnstoni", title: "Okapi", category: "Africa" },
  { id: "meerkat", name: "Suricata suricatta", title: "Meerkat", category: "Africa" },
  { id: "honey-badger", name: "Mellivora capensis", title: "Honey badger", category: "Africa" },
  { id: "aardvark", name: "Orycteropus afer", title: "Aardvark", category: "Africa" },
  { id: "pangolin", name: "Smutsia temminckii", title: "Temminck's pangolin", category: "Africa" },
  { id: "nile-croc", name: "Crocodylus niloticus", title: "Nile crocodile", category: "Africa" },
  { id: "black-mamba", name: "Dendroaspis polylepis", title: "Black mamba", category: "Africa" },
  { id: "ostrich", name: "Struthio camelus", title: "Common ostrich", category: "Africa" },
  { id: "secretary-bird", name: "Sagittarius serpentarius", title: "Secretary bird", category: "Africa" },
  { id: "fish-eagle", name: "Haliaeetus vocifer", title: "African fish eagle", category: "Africa" },
  { id: "shoebill", name: "Balaeniceps rex", title: "Shoebill", category: "Africa" },
  { id: "crowned-crane", name: "Balearica regulorum", title: "Grey crowned crane", category: "Africa" },
  { id: "lesser-flamingo", name: "Phoeniconaias minor", title: "Lesser flamingo", category: "Africa" },
  { id: "greater-flamingo", name: "Phoenicopterus roseus", title: "Greater flamingo", category: "Africa" },
  // Asia
  { id: "tiger", name: "Panthera tigris", title: "Tiger", category: "Asia" },
  { id: "snow-leopard", name: "Panthera uncia", title: "Snow leopard", category: "Asia" },
  { id: "clouded-leopard", name: "Neofelis nebulosa", title: "Clouded leopard", category: "Asia" },
  { id: "asian-elephant", name: "Elephas maximus", title: "Asian elephant", category: "Asia" },
  { id: "indian-rhino", name: "Rhinoceros unicornis", title: "Indian rhinoceros", category: "Asia" },
  { id: "red-panda", name: "Ailurus fulgens", title: "Red panda", category: "Asia" },
  { id: "bornean-orangutan", name: "Pongo pygmaeus", title: "Bornean orangutan", category: "Asia" },
  { id: "sumatran-orangutan", name: "Pongo abelii", title: "Sumatran orangutan", category: "Asia" },
  { id: "lar-gibbon", name: "Hylobates lar", title: "Lar gibbon", category: "Asia" },
  { id: "proboscis-monkey", name: "Nasalis larvatus", title: "Proboscis monkey", category: "Asia" },
  { id: "japanese-macaque", name: "Macaca fuscata", title: "Japanese macaque", category: "Asia" },
  { id: "dhole", name: "Cuon alpinus", title: "Dhole", category: "Asia" },
  { id: "binturong", name: "Arctictis binturong", title: "Binturong", category: "Asia" },
  { id: "komodo", name: "Varanus komodoensis", title: "Komodo dragon", category: "Asia" },
  { id: "king-cobra", name: "Ophiophagus hannah", title: "King cobra", category: "Asia" },
  { id: "reticulated-python", name: "Malayopython reticulatus", title: "Reticulated python", category: "Asia" },
  { id: "gaur", name: "Bos gaurus", title: "Gaur", category: "Asia" },
  { id: "wild-yak", name: "Bos mutus", title: "Wild yak", category: "Asia" },
  { id: "markhor", name: "Capra falconeri", title: "Markhor", category: "Asia" },
  { id: "siberian-ibex", name: "Capra sibirica", title: "Siberian ibex", category: "Asia" },
  { id: "argali", name: "Ovis ammon", title: "Argali", category: "Asia" },
  { id: "bharal", name: "Pseudois nayaur", title: "Bharal (blue sheep)", category: "Asia" },
  { id: "himalayan-tahr", name: "Hemitragus jemlahicus", title: "Himalayan tahr", category: "Asia" },
  { id: "saiga", name: "Saiga tatarica", title: "Saiga antelope", category: "Asia" },
  { id: "przewalski", name: "Equus przewalskii", title: "Przewalski's horse", category: "Asia" },
  { id: "bactrian-camel", name: "Camelus ferus", title: "Wild Bactrian camel", category: "Asia" },
  { id: "peafowl", name: "Pavo cristatus", title: "Indian peafowl", category: "Asia" },
  { id: "red-crowned-crane", name: "Grus japonensis", title: "Red-crowned crane", category: "Asia" },
  { id: "himalayan-monal", name: "Lophophorus impejanus", title: "Himalayan monal", category: "Asia" },
  { id: "great-hornbill", name: "Buceros bicornis", title: "Great hornbill", category: "Asia" },
  // Europe
  { id: "red-deer", name: "Cervus elaphus", title: "Red deer", category: "Europe" },
  { id: "roe-deer", name: "Capreolus capreolus", title: "Roe deer", category: "Europe" },
  { id: "fallow-deer", name: "Dama dama", title: "Fallow deer", category: "Europe" },
  { id: "wild-boar", name: "Sus scrofa", title: "Wild boar", category: "Europe" },
  { id: "wisent", name: "Bison bonasus", title: "European bison", category: "Europe" },
  { id: "chamois", name: "Rupicapra rupicapra", title: "Chamois", category: "Europe" },
  { id: "alpine-ibex", name: "Capra ibex", title: "Alpine ibex", category: "Europe" },
  { id: "mouflon", name: "Ovis gmelini", title: "Mouflon", category: "Europe" },
  { id: "eurasian-lynx", name: "Lynx lynx", title: "Eurasian lynx", category: "Europe" },
  { id: "iberian-lynx", name: "Lynx pardinus", title: "Iberian lynx", category: "Europe" },
  { id: "euro-badger", name: "Meles meles", title: "European badger", category: "Europe" },
  { id: "red-squirrel", name: "Sciurus vulgaris", title: "Red squirrel", category: "Europe" },
  { id: "euro-pine-marten", name: "Martes martes", title: "European pine marten", category: "Europe" },
  { id: "hedgehog", name: "Erinaceus europaeus", title: "European hedgehog", category: "Europe" },
  { id: "brown-hare", name: "Lepus europaeus", title: "Brown hare", category: "Europe" },
  { id: "capercaillie", name: "Tetrao urogallus", title: "Western capercaillie", category: "Europe" },
  { id: "black-grouse", name: "Lyrurus tetrix", title: "Black grouse", category: "Europe" },
  { id: "rock-ptarmigan", name: "Lagopus muta", title: "Rock ptarmigan", category: "Europe" },
  { id: "grey-partridge", name: "Perdix perdix", title: "Grey partridge", category: "Europe" },
  { id: "white-stork", name: "Ciconia ciconia", title: "White stork", category: "Europe" },
  { id: "common-crane", name: "Grus grus", title: "Common crane", category: "Europe" },
  { id: "griffon-vulture", name: "Gyps fulvus", title: "Griffon vulture", category: "Europe" },
  { id: "lammergeier", name: "Gypaetus barbatus", title: "Bearded vulture", category: "Europe" },
  { id: "eagle-owl", name: "Bubo bubo", title: "Eurasian eagle-owl", category: "Europe" },
  { id: "white-tailed-eagle", name: "Haliaeetus albicilla", title: "White-tailed eagle", category: "Europe" },
  // South & Central America
  { id: "jaguar", name: "Panthera onca", title: "Jaguar", category: "South & Central America" },
  { id: "ocelot", name: "Leopardus pardalis", title: "Ocelot", category: "South & Central America" },
  { id: "maned-wolf", name: "Chrysocyon brachyurus", title: "Maned wolf", category: "South & Central America" },
  { id: "giant-anteater", name: "Myrmecophaga tridactyla", title: "Giant anteater", category: "South & Central America" },
  { id: "capybara", name: "Hydrochoerus hydrochaeris", title: "Capybara", category: "South & Central America" },
  { id: "lowland-tapir", name: "Tapirus terrestris", title: "Lowland tapir", category: "South & Central America" },
  { id: "bairds-tapir", name: "Tapirus bairdii", title: "Baird's tapir", category: "South & Central America" },
  { id: "guanaco", name: "Lama guanicoe", title: "Guanaco", category: "South & Central America" },
  { id: "vicuna", name: "Vicugna vicugna", title: "Vicuña", category: "South & Central America" },
  { id: "giant-otter", name: "Pteronura brasiliensis", title: "Giant otter", category: "South & Central America" },
  { id: "three-toed-sloth", name: "Bradypus variegatus", title: "Brown-throated sloth", category: "South & Central America" },
  { id: "giant-armadillo", name: "Priodontes maximus", title: "Giant armadillo", category: "South & Central America" },
  { id: "golden-lion-tamarin", name: "Leontopithecus rosalia", title: "Golden lion tamarin", category: "South & Central America" },
  { id: "black-howler", name: "Alouatta caraya", title: "Black howler monkey", category: "South & Central America" },
  { id: "spider-monkey", name: "Ateles geoffroyi", title: "Geoffroy's spider monkey", category: "South & Central America" },
  { id: "andean-condor", name: "Vultur gryphus", title: "Andean condor", category: "South & Central America" },
  { id: "harpy-eagle", name: "Harpia harpyja", title: "Harpy eagle", category: "South & Central America" },
  { id: "toco-toucan", name: "Ramphastos toco", title: "Toco toucan", category: "South & Central America" },
  { id: "scarlet-macaw", name: "Ara macao", title: "Scarlet macaw", category: "South & Central America" },
  { id: "hyacinth-macaw", name: "Anodorhynchus hyacinthinus", title: "Hyacinth macaw", category: "South & Central America" },
  { id: "hoatzin", name: "Opisthocomus hoazin", title: "Hoatzin", category: "South & Central America" },
  { id: "greater-rhea", name: "Rhea americana", title: "Greater rhea", category: "South & Central America" },
  { id: "quetzal", name: "Pharomachrus mocinno", title: "Resplendent quetzal", category: "South & Central America" },
  { id: "anaconda", name: "Eunectes murinus", title: "Green anaconda", category: "South & Central America" },
  { id: "black-caiman", name: "Melanosuchus niger", title: "Black caiman", category: "South & Central America" },
  { id: "poison-frog", name: "Dendrobates tinctorius", title: "Dyeing poison frog", category: "South & Central America" },
  { id: "arapaima", name: "Arapaima gigas", title: "Arapaima", category: "South & Central America" },
  { id: "piranha", name: "Pygocentrus nattereri", title: "Red-bellied piranha", category: "South & Central America" },
  { id: "peacock-bass", name: "Cichla ocellaris", title: "Peacock bass", category: "South & Central America" },
  { id: "golden-dorado", name: "Salminus brasiliensis", title: "Golden dorado", category: "South & Central America" },
  { id: "river-dolphin", name: "Inia geoffrensis", title: "Amazon river dolphin", category: "South & Central America" },
  // Australia & Oceania
  { id: "red-kangaroo", name: "Osphranter rufus", title: "Red kangaroo", category: "Australia & Oceania" },
  { id: "grey-kangaroo", name: "Macropus giganteus", title: "Eastern grey kangaroo", category: "Australia & Oceania" },
  { id: "koala", name: "Phascolarctos cinereus", title: "Koala", category: "Australia & Oceania" },
  { id: "wombat", name: "Vombatus ursinus", title: "Common wombat", category: "Australia & Oceania" },
  { id: "tasmanian-devil", name: "Sarcophilus harrisii", title: "Tasmanian devil", category: "Australia & Oceania" },
  { id: "platypus", name: "Ornithorhynchus anatinus", title: "Platypus", category: "Australia & Oceania" },
  { id: "echidna", name: "Tachyglossus aculeatus", title: "Short-beaked echidna", category: "Australia & Oceania" },
  { id: "sugar-glider", name: "Petaurus breviceps", title: "Sugar glider", category: "Australia & Oceania" },
  { id: "quokka", name: "Setonix brachyurus", title: "Quokka", category: "Australia & Oceania" },
  { id: "numbat", name: "Myrmecobius fasciatus", title: "Numbat", category: "Australia & Oceania" },
  { id: "emu", name: "Dromaius novaehollandiae", title: "Emu", category: "Australia & Oceania" },
  { id: "cassowary", name: "Casuarius casuarius", title: "Southern cassowary", category: "Australia & Oceania" },
  { id: "kookaburra", name: "Dacelo novaeguineae", title: "Laughing kookaburra", category: "Australia & Oceania" },
  { id: "kea", name: "Nestor notabilis", title: "Kea", category: "Australia & Oceania" },
  { id: "kakapo", name: "Strigops habroptilus", title: "Kakapo", category: "Australia & Oceania" },
  { id: "kiwi", name: "Apteryx mantelli", title: "North Island brown kiwi", category: "Australia & Oceania" },
  { id: "tuatara", name: "Sphenodon punctatus", title: "Tuatara", category: "Australia & Oceania" },
  { id: "saltwater-croc", name: "Crocodylus porosus", title: "Saltwater crocodile", category: "Australia & Oceania" },
  { id: "frilled-lizard", name: "Chlamydosaurus kingii", title: "Frilled lizard", category: "Australia & Oceania" },
  { id: "barramundi", name: "Lates calcarifer", title: "Barramundi", category: "Australia & Oceania" },
  // Arctic & Antarctic
  { id: "muskox", name: "Ovibos moschatus", title: "Muskox", category: "Arctic & Antarctic" },
  { id: "arctic-fox", name: "Vulpes lagopus", title: "Arctic fox", category: "Arctic & Antarctic" },
  { id: "arctic-hare", name: "Lepus arcticus", title: "Arctic hare", category: "Arctic & Antarctic" },
  { id: "walrus", name: "Odobenus rosmarus", title: "Walrus", category: "Arctic & Antarctic" },
  { id: "narwhal", name: "Monodon monoceros", title: "Narwhal", category: "Arctic & Antarctic" },
  { id: "beluga", name: "Delphinapterus leucas", title: "Beluga", category: "Arctic & Antarctic" },
  { id: "bowhead", name: "Balaena mysticetus", title: "Bowhead whale", category: "Arctic & Antarctic" },
  { id: "harp-seal", name: "Pagophilus groenlandicus", title: "Harp seal", category: "Arctic & Antarctic" },
  { id: "leopard-seal", name: "Hydrurga leptonyx", title: "Leopard seal", category: "Arctic & Antarctic" },
  { id: "emperor-penguin", name: "Aptenodytes forsteri", title: "Emperor penguin", category: "Arctic & Antarctic" },
  { id: "king-penguin", name: "Aptenodytes patagonicus", title: "King penguin", category: "Arctic & Antarctic" },
  { id: "adelie-penguin", name: "Pygoscelis adeliae", title: "Adélie penguin", category: "Arctic & Antarctic" },
  { id: "willow-ptarmigan", name: "Lagopus lagopus", title: "Willow ptarmigan", category: "Arctic & Antarctic" },
  // Ocean giants
  { id: "blue-whale", name: "Balaenoptera musculus", title: "Blue whale", category: "Ocean giants" },
  { id: "fin-whale", name: "Balaenoptera physalus", title: "Fin whale", category: "Ocean giants" },
  { id: "sperm-whale", name: "Physeter macrocephalus", title: "Sperm whale", category: "Ocean giants" },
  { id: "right-whale", name: "Eubalaena glacialis", title: "North Atlantic right whale", category: "Ocean giants" },
  { id: "great-white", name: "Carcharodon carcharias", title: "Great white shark", category: "Ocean giants" },
  { id: "whale-shark", name: "Rhincodon typus", title: "Whale shark", category: "Ocean giants" },
  { id: "tiger-shark", name: "Galeocerdo cuvier", title: "Tiger shark", category: "Ocean giants" },
  { id: "hammerhead", name: "Sphyrna mokarran", title: "Great hammerhead", category: "Ocean giants" },
  { id: "mako", name: "Isurus oxyrinchus", title: "Shortfin mako", category: "Ocean giants" },
  { id: "manta", name: "Mobula birostris", title: "Giant manta ray", category: "Ocean giants" },
  { id: "bluefin", name: "Thunnus thynnus", title: "Atlantic bluefin tuna", category: "Ocean giants" },
  { id: "sailfish", name: "Istiophorus platypterus", title: "Sailfish", category: "Ocean giants" },
  { id: "blue-marlin", name: "Makaira nigricans", title: "Blue marlin", category: "Ocean giants" },
  { id: "swordfish", name: "Xiphias gladius", title: "Swordfish", category: "Ocean giants" },
  { id: "mahi", name: "Coryphaena hippurus", title: "Mahi-mahi", category: "Ocean giants" },
  { id: "sunfish", name: "Mola mola", title: "Ocean sunfish", category: "Ocean giants" },
  { id: "leatherback", name: "Dermochelys coriacea", title: "Leatherback sea turtle", category: "Ocean giants" },
  { id: "green-turtle", name: "Chelonia mydas", title: "Green sea turtle", category: "Ocean giants" },
  { id: "loggerhead", name: "Caretta caretta", title: "Loggerhead sea turtle", category: "Ocean giants" },
  // Long-distance birds
  { id: "arctic-tern", name: "Sterna paradisaea", title: "Arctic tern", category: "Long-distance birds" },
  { id: "godwit", name: "Limosa lapponica", title: "Bar-tailed godwit", category: "Long-distance birds" },
  { id: "red-knot", name: "Calidris canutus", title: "Red knot", category: "Long-distance birds" },
  { id: "sooty-shearwater", name: "Ardenna grisea", title: "Sooty shearwater", category: "Long-distance birds" },
  { id: "common-swift", name: "Apus apus", title: "Common swift", category: "Long-distance birds" },
  { id: "amur-falcon", name: "Falco amurensis", title: "Amur falcon", category: "Long-distance birds" },
  { id: "swainsons-hawk", name: "Buteo swainsoni", title: "Swainson's hawk", category: "Long-distance birds" },
  { id: "wandering-albatross", name: "Diomedea exulans", title: "Wandering albatross", category: "Long-distance birds" },
  // Historical (museum records)
  { id: "dodo", name: "Raphus cucullatus", title: "Dodo (museum records)", category: "Historical" },
  { id: "great-auk", name: "Pinguinus impennis", title: "Great auk (museum records)", category: "Historical" },
  { id: "thylacine", name: "Thylacinus cynocephalus", title: "Thylacine (museum records)", category: "Historical" },
  { id: "carolina-parakeet", name: "Conuropsis carolinensis", title: "Carolina parakeet (museum records)", category: "Historical" },
  { id: "stellers-sea-cow", name: "Hydrodamalis gigas", title: "Steller's sea cow (museum records)", category: "Historical" },
  { id: "ivory-billed", name: "Campephilus principalis", title: "Ivory-billed woodpecker (museum records)", category: "Historical" },
  // ---- Wave 2 (curated) ----
  { id: "northern-cardinal", name: "Cardinalis cardinalis", title: "Northern Cardinal", category: "Songbirds" },
  { id: "blue-jay", name: "Cyanocitta cristata", title: "Blue Jay", category: "Songbirds" },
  { id: "black-capped-chickadee", name: "Poecile atricapillus", title: "Black-capped Chickadee", category: "Songbirds" },
  { id: "american-robin", name: "Turdus migratorius", title: "American Robin", category: "Songbirds" },
  { id: "eastern-bluebird", name: "Sialia sialis", title: "Eastern Bluebird", category: "Songbirds" },
  { id: "baltimore-oriole", name: "Icterus galbula", title: "Baltimore Oriole", category: "Songbirds" },
  { id: "scarlet-tanager", name: "Piranga olivacea", title: "Scarlet Tanager", category: "Songbirds" },
  { id: "cedar-waxwing", name: "Bombycilla cedrorum", title: "Cedar Waxwing", category: "Songbirds" },
  { id: "red-winged-blackbird", name: "Agelaius phoeniceus", title: "Red-winged Blackbird", category: "Songbirds" },
  { id: "northern-mockingbird", name: "Mimus polyglottos", title: "Northern Mockingbird", category: "Songbirds" },
  { id: "american-goldfinch", name: "Spinus tristis", title: "American Goldfinch", category: "Songbirds" },
  { id: "common-raven", name: "Corvus corax", title: "Common Raven", category: "Songbirds" },
  { id: "black-billed-magpie", name: "Pica hudsonia", title: "Black-billed Magpie", category: "Songbirds" },
  { id: "european-robin", name: "Erithacus rubecula", title: "European Robin", category: "Songbirds" },
  { id: "common-nightingale", name: "Luscinia megarhynchos", title: "Common Nightingale", category: "Songbirds" },
  { id: "eurasian-blue-tit", name: "Cyanistes caeruleus", title: "Eurasian Blue Tit", category: "Songbirds" },
  { id: "great-tit", name: "Parus major", title: "Great Tit", category: "Songbirds" },
  { id: "eurasian-blackbird", name: "Turdus merula", title: "Eurasian Blackbird", category: "Songbirds" },
  { id: "european-goldfinch", name: "Carduelis carduelis", title: "European Goldfinch", category: "Songbirds" },
  { id: "common-chaffinch", name: "Fringilla coelebs", title: "Common Chaffinch", category: "Songbirds" },
  { id: "eurasian-magpie", name: "Pica pica", title: "Eurasian Magpie", category: "Songbirds" },
  { id: "eurasian-hoopoe", name: "Upupa epops", title: "Eurasian Hoopoe", category: "Songbirds" },
  { id: "eurasian-wren", name: "Troglodytes troglodytes", title: "Eurasian Wren", category: "Songbirds" },
  { id: "superb-fairywren", name: "Malurus cyaneus", title: "Superb Fairywren", category: "Songbirds" },
  { id: "superb-lyrebird", name: "Menura novaehollandiae", title: "Superb Lyrebird", category: "Songbirds" },
  { id: "australian-magpie", name: "Gymnorhina tibicen", title: "Australian Magpie", category: "Songbirds" },
  { id: "oriental-magpie-robin", name: "Copsychus saularis", title: "Oriental Magpie-Robin", category: "Songbirds" },
  { id: "blue-gray-tanager", name: "Thraupis episcopus", title: "Blue-gray Tanager", category: "Songbirds" },
  { id: "barn-owl", name: "Tyto alba", title: "Barn Owl", category: "Raptors" },
  { id: "great-grey-owl", name: "Strix nebulosa", title: "Great Grey Owl", category: "Raptors" },
  { id: "barred-owl", name: "Strix varia", title: "Barred Owl", category: "Raptors" },
  { id: "tawny-owl", name: "Strix aluco", title: "Tawny Owl", category: "Raptors" },
  { id: "burrowing-owl", name: "Athene cunicularia", title: "Burrowing Owl", category: "Raptors" },
  { id: "saw-whet-owl", name: "Aegolius acadicus", title: "Northern Saw-whet Owl", category: "Raptors" },
  { id: "boreal-owl", name: "Aegolius funereus", title: "Boreal Owl", category: "Raptors" },
  { id: "eastern-screech-owl", name: "Megascops asio", title: "Eastern Screech-Owl", category: "Raptors" },
  { id: "blakistons-fish-owl", name: "Bubo blakistoni", title: "Blakiston's Fish Owl", category: "Raptors" },
  { id: "gyrfalcon", name: "Falco rusticolus", title: "Gyrfalcon", category: "Raptors" },
  { id: "american-kestrel", name: "Falco sparverius", title: "American Kestrel", category: "Raptors" },
  { id: "merlin", name: "Falco columbarius", title: "Merlin", category: "Raptors" },
  { id: "coopers-hawk", name: "Accipiter cooperii", title: "Cooper's Hawk", category: "Raptors" },
  { id: "sharp-shinned-hawk", name: "Accipiter striatus", title: "Sharp-shinned Hawk", category: "Raptors" },
  { id: "northern-harrier", name: "Circus hudsonius", title: "Northern Harrier", category: "Raptors" },
  { id: "ferruginous-hawk", name: "Buteo regalis", title: "Ferruginous Hawk", category: "Raptors" },
  { id: "rough-legged-hawk", name: "Buteo lagopus", title: "Rough-legged Hawk", category: "Raptors" },
  { id: "stellers-sea-eagle", name: "Haliaeetus pelagicus", title: "Steller's Sea Eagle", category: "Raptors" },
  { id: "martial-eagle", name: "Polemaetus bellicosus", title: "Martial Eagle", category: "Raptors" },
  { id: "crowned-eagle", name: "Stephanoaetus coronatus", title: "Crowned Eagle", category: "Raptors" },
  { id: "philippine-eagle", name: "Pithecophaga jefferyi", title: "Philippine Eagle", category: "Raptors" },
  { id: "black-kite", name: "Milvus migrans", title: "Black Kite", category: "Raptors" },
  { id: "turkey-vulture", name: "Cathartes aura", title: "Turkey Vulture", category: "Raptors" },
  { id: "california-condor", name: "Gymnogyps californianus", title: "California Condor", category: "Raptors" },
  { id: "great-blue-heron", name: "Ardea herodias", title: "Great Blue Heron", category: "Waterbirds & shorebirds" },
  { id: "great-egret", name: "Ardea alba", title: "Great Egret", category: "Waterbirds & shorebirds" },
  { id: "snowy-egret", name: "Egretta thula", title: "Snowy Egret", category: "Waterbirds & shorebirds" },
  { id: "american-white-pelican", name: "Pelecanus erythrorhynchos", title: "American White Pelican", category: "Waterbirds & shorebirds" },
  { id: "brown-pelican", name: "Pelecanus occidentalis", title: "Brown Pelican", category: "Waterbirds & shorebirds" },
  { id: "double-crested-cormorant", name: "Nannopterum auritum", title: "Double-crested Cormorant", category: "Waterbirds & shorebirds" },
  { id: "anhinga", name: "Anhinga anhinga", title: "Anhinga", category: "Waterbirds & shorebirds" },
  { id: "roseate-spoonbill", name: "Platalea ajaja", title: "Roseate Spoonbill", category: "Waterbirds & shorebirds" },
  { id: "wood-stork", name: "Mycteria americana", title: "Wood Stork", category: "Waterbirds & shorebirds" },
  { id: "atlantic-puffin", name: "Fratercula arctica", title: "Atlantic Puffin", category: "Waterbirds & shorebirds" },
  { id: "northern-gannet", name: "Morus bassanus", title: "Northern Gannet", category: "Waterbirds & shorebirds" },
  { id: "common-murre", name: "Uria aalge", title: "Common Murre", category: "Waterbirds & shorebirds" },
  { id: "black-skimmer", name: "Rynchops niger", title: "Black Skimmer", category: "Waterbirds & shorebirds" },
  { id: "american-oystercatcher", name: "Haematopus palliatus", title: "American Oystercatcher", category: "Waterbirds & shorebirds" },
  { id: "american-avocet", name: "Recurvirostra americana", title: "American Avocet", category: "Waterbirds & shorebirds" },
  { id: "killdeer", name: "Charadrius vociferus", title: "Killdeer", category: "Waterbirds & shorebirds" },
  { id: "long-billed-curlew", name: "Numenius americanus", title: "Long-billed Curlew", category: "Waterbirds & shorebirds" },
  { id: "whimbrel", name: "Numenius phaeopus", title: "Whimbrel", category: "Waterbirds & shorebirds" },
  { id: "piping-plover", name: "Charadrius melodus", title: "Piping Plover", category: "Waterbirds & shorebirds" },
  { id: "common-tern", name: "Sterna hirundo", title: "Common Tern", category: "Waterbirds & shorebirds" },
  { id: "laughing-gull", name: "Leucophaeus atricilla", title: "Laughing Gull", category: "Waterbirds & shorebirds" },
  { id: "magnificent-frigatebird", name: "Fregata magnificens", title: "Magnificent Frigatebird", category: "Waterbirds & shorebirds" },
  { id: "blue-footed-booby", name: "Sula nebouxii", title: "Blue-footed Booby", category: "Waterbirds & shorebirds" },
  { id: "king-eider", name: "Somateria spectabilis", title: "King Eider", category: "Waterbirds & shorebirds" },
  { id: "harlequin-duck", name: "Histrionicus histrionicus", title: "Harlequin Duck", category: "Waterbirds & shorebirds" },
  { id: "common-goldeneye", name: "Bucephala clangula", title: "Common Goldeneye", category: "Waterbirds & shorebirds" },
  { id: "western-diamondback", name: "Crotalus atrox", title: "Western Diamondback Rattlesnake", category: "Reptiles & amphibians" },
  { id: "eastern-diamondback", name: "Crotalus adamanteus", title: "Eastern Diamondback Rattlesnake", category: "Reptiles & amphibians" },
  { id: "prairie-rattlesnake", name: "Crotalus viridis", title: "Prairie Rattlesnake", category: "Reptiles & amphibians" },
  { id: "copperhead", name: "Agkistrodon contortrix", title: "Eastern Copperhead", category: "Reptiles & amphibians" },
  { id: "cottonmouth", name: "Agkistrodon piscivorus", title: "Cottonmouth", category: "Reptiles & amphibians" },
  { id: "eastern-indigo-snake", name: "Drymarchon couperi", title: "Eastern Indigo Snake", category: "Reptiles & amphibians" },
  { id: "corn-snake", name: "Pantherophis guttatus", title: "Corn Snake", category: "Reptiles & amphibians" },
  { id: "common-garter-snake", name: "Thamnophis sirtalis", title: "Common Garter Snake", category: "Reptiles & amphibians" },
  { id: "boa-constrictor", name: "Boa constrictor", title: "Boa Constrictor", category: "Reptiles & amphibians" },
  { id: "ball-python", name: "Python regius", title: "Ball Python", category: "Reptiles & amphibians" },
  { id: "gaboon-viper", name: "Bitis gabonica", title: "Gaboon Viper", category: "Reptiles & amphibians" },
  { id: "puff-adder", name: "Bitis arietans", title: "Puff Adder", category: "Reptiles & amphibians" },
  { id: "green-mamba", name: "Dendroaspis angusticeps", title: "Eastern Green Mamba", category: "Reptiles & amphibians" },
  { id: "inland-taipan", name: "Oxyuranus microlepidotus", title: "Inland Taipan", category: "Reptiles & amphibians" },
  { id: "eastern-brown-snake", name: "Pseudonaja textilis", title: "Eastern Brown Snake", category: "Reptiles & amphibians" },
  { id: "gila-monster", name: "Heloderma suspectum", title: "Gila Monster", category: "Reptiles & amphibians" },
  { id: "green-iguana", name: "Iguana iguana", title: "Green Iguana", category: "Reptiles & amphibians" },
  { id: "marine-iguana", name: "Amblyrhynchus cristatus", title: "Marine Iguana", category: "Reptiles & amphibians" },
  { id: "panther-chameleon", name: "Furcifer pardalis", title: "Panther Chameleon", category: "Reptiles & amphibians" },
  { id: "veiled-chameleon", name: "Chamaeleo calyptratus", title: "Veiled Chameleon", category: "Reptiles & amphibians" },
  { id: "leopard-gecko", name: "Eublepharis macularius", title: "Leopard Gecko", category: "Reptiles & amphibians" },
  { id: "bearded-dragon", name: "Pogona vitticeps", title: "Central Bearded Dragon", category: "Reptiles & amphibians" },
  { id: "perentie", name: "Varanus giganteus", title: "Perentie", category: "Reptiles & amphibians" },
  { id: "nile-monitor", name: "Varanus niloticus", title: "Nile Monitor", category: "Reptiles & amphibians" },
  { id: "american-bullfrog", name: "Lithobates catesbeianus", title: "American Bullfrog", category: "Reptiles & amphibians" },
  { id: "spring-peeper", name: "Pseudacris crucifer", title: "Spring Peeper", category: "Reptiles & amphibians" },
  { id: "red-eyed-tree-frog", name: "Agalychnis callidryas", title: "Red-eyed Tree Frog", category: "Reptiles & amphibians" },
  { id: "golden-poison-frog", name: "Phyllobates terribilis", title: "Golden Poison Frog", category: "Reptiles & amphibians" },
  { id: "cane-toad", name: "Rhinella marina", title: "Cane Toad", category: "Reptiles & amphibians" },
  { id: "american-toad", name: "Anaxyrus americanus", title: "American Toad", category: "Reptiles & amphibians" },
  { id: "common-frog", name: "Rana temporaria", title: "Common Frog", category: "Reptiles & amphibians" },
  { id: "whites-tree-frog", name: "Litoria caerulea", title: "White's Tree Frog", category: "Reptiles & amphibians" },
  { id: "hellbender", name: "Cryptobranchus alleganiensis", title: "Hellbender", category: "Reptiles & amphibians" },
  { id: "axolotl", name: "Ambystoma mexicanum", title: "Axolotl", category: "Reptiles & amphibians" },
  { id: "tiger-salamander", name: "Ambystoma tigrinum", title: "Eastern Tiger Salamander", category: "Reptiles & amphibians" },
  { id: "red-spotted-newt", name: "Notophthalmus viridescens", title: "Red-spotted Newt", category: "Reptiles & amphibians" },
  { id: "spotted-salamander", name: "Ambystoma maculatum", title: "Spotted Salamander", category: "Reptiles & amphibians" },
  { id: "fire-salamander", name: "Salamandra salamandra", title: "Fire Salamander", category: "Reptiles & amphibians" },
  { id: "eastern-box-turtle", name: "Terrapene carolina", title: "Eastern Box Turtle", category: "Reptiles & amphibians" },
  { id: "painted-turtle", name: "Chrysemys picta", title: "Painted Turtle", category: "Reptiles & amphibians" },
  { id: "alligator-snapping-turtle", name: "Macrochelys temminckii", title: "Alligator Snapping Turtle", category: "Reptiles & amphibians" },
  { id: "blandings-turtle", name: "Emydoidea blandingii", title: "Blanding's Turtle", category: "Reptiles & amphibians" },
  { id: "diamondback-terrapin", name: "Malaclemys terrapin", title: "Diamondback Terrapin", category: "Reptiles & amphibians" },
  { id: "galapagos-tortoise", name: "Chelonoidis niger", title: "Galapagos Giant Tortoise", category: "Reptiles & amphibians" },
  { id: "gopher-tortoise", name: "Gopherus polyphemus", title: "Gopher Tortoise", category: "Reptiles & amphibians" },
  { id: "leopard-tortoise", name: "Stigmochelys pardalis", title: "Leopard Tortoise", category: "Reptiles & amphibians" },
  { id: "bull-shark", name: "Carcharhinus leucas", title: "Bull Shark", category: "Saltwater" },
  { id: "blacktip-shark", name: "Carcharhinus limbatus", title: "Blacktip Shark", category: "Saltwater" },
  { id: "nurse-shark", name: "Ginglymostoma cirratum", title: "Nurse Shark", category: "Saltwater" },
  { id: "lemon-shark", name: "Negaprion brevirostris", title: "Lemon Shark", category: "Saltwater" },
  { id: "thresher-shark", name: "Alopias vulpinus", title: "Common Thresher Shark", category: "Saltwater" },
  { id: "oceanic-whitetip", name: "Carcharhinus longimanus", title: "Oceanic Whitetip Shark", category: "Saltwater" },
  { id: "blue-shark", name: "Prionace glauca", title: "Blue Shark", category: "Saltwater" },
  { id: "spiny-dogfish", name: "Squalus acanthias", title: "Spiny Dogfish", category: "Saltwater" },
  { id: "southern-stingray", name: "Hypanus americanus", title: "Southern Stingray", category: "Saltwater" },
  { id: "spotted-eagle-ray", name: "Aetobatus narinari", title: "Spotted Eagle Ray", category: "Saltwater" },
  { id: "smalltooth-sawfish", name: "Pristis pectinata", title: "Smalltooth Sawfish", category: "Saltwater" },
  { id: "goliath-grouper", name: "Epinephelus itajara", title: "Atlantic Goliath Grouper", category: "Saltwater" },
  { id: "red-snapper", name: "Lutjanus campechanus", title: "Red Snapper", category: "Saltwater" },
  { id: "striped-bass", name: "Morone saxatilis", title: "Striped Bass", category: "Saltwater" },
  { id: "bluefish", name: "Pomatomus saltatrix", title: "Bluefish", category: "Saltwater" },
  { id: "red-drum", name: "Sciaenops ocellatus", title: "Red Drum", category: "Saltwater" },
  { id: "spotted-seatrout", name: "Cynoscion nebulosus", title: "Spotted Seatrout", category: "Saltwater" },
  { id: "permit", name: "Trachinotus falcatus", title: "Permit", category: "Saltwater" },
  { id: "roosterfish", name: "Nematistius pectoralis", title: "Roosterfish", category: "Saltwater" },
  { id: "giant-trevally", name: "Caranx ignobilis", title: "Giant Trevally", category: "Saltwater" },
  { id: "wahoo", name: "Acanthocybium solandri", title: "Wahoo", category: "Saltwater" },
  { id: "yellowfin-tuna", name: "Thunnus albacares", title: "Yellowfin Tuna", category: "Saltwater" },
  { id: "albacore", name: "Thunnus alalunga", title: "Albacore", category: "Saltwater" },
  { id: "atlantic-cod", name: "Gadus morhua", title: "Atlantic Cod", category: "Saltwater" },
  { id: "pacific-halibut", name: "Hippoglossus stenolepis", title: "Pacific Halibut", category: "Saltwater" },
  { id: "false-albacore", name: "Euthynnus alletteratus", title: "False Albacore", category: "Saltwater" },
  { id: "arctic-grayling", name: "Thymallus arcticus", title: "Arctic Grayling", category: "Fish" },
  { id: "dolly-varden", name: "Salvelinus malma", title: "Dolly Varden", category: "Fish" },
  { id: "bull-trout", name: "Salvelinus confluentus", title: "Bull Trout", category: "Fish" },
  { id: "golden-trout", name: "Oncorhynchus aguabonita", title: "Golden Trout", category: "Fish" },
  { id: "coho-salmon", name: "Oncorhynchus kisutch", title: "Coho Salmon", category: "Fish" },
  { id: "sockeye-salmon", name: "Oncorhynchus nerka", title: "Sockeye Salmon", category: "Fish" },
  { id: "pink-salmon", name: "Oncorhynchus gorbuscha", title: "Pink Salmon", category: "Fish" },
  { id: "chum-salmon", name: "Oncorhynchus keta", title: "Chum Salmon", category: "Fish" },
  { id: "siberian-taimen", name: "Hucho taimen", title: "Siberian Taimen", category: "Fish" },
  { id: "huchen", name: "Hucho hucho", title: "Huchen", category: "Fish" },
  { id: "african-tigerfish", name: "Hydrocynus vittatus", title: "African Tigerfish", category: "Fish" },
  { id: "nile-perch", name: "Lates niloticus", title: "Nile Perch", category: "Fish" },
  { id: "golden-mahseer", name: "Tor putitora", title: "Golden Mahseer", category: "Fish" },
  { id: "wels-catfish", name: "Silurus glanis", title: "Wels Catfish", category: "Fish" },
  { id: "blue-catfish", name: "Ictalurus furcatus", title: "Blue Catfish", category: "Fish" },
  { id: "flathead-catfish", name: "Pylodictis olivaris", title: "Flathead Catfish", category: "Fish" },
  { id: "channel-catfish", name: "Ictalurus punctatus", title: "Channel Catfish", category: "Fish" },
  { id: "white-sturgeon", name: "Acipenser transmontanus", title: "White Sturgeon", category: "Fish" },
  { id: "lake-sturgeon", name: "Acipenser fulvescens", title: "Lake Sturgeon", category: "Fish" },
  { id: "alligator-gar", name: "Atractosteus spatula", title: "Alligator Gar", category: "Fish" },
  { id: "longnose-gar", name: "Lepisosteus osseus", title: "Longnose Gar", category: "Fish" },
  { id: "bluegill", name: "Lepomis macrochirus", title: "Bluegill", category: "Fish" },
  { id: "black-crappie", name: "Pomoxis nigromaculatus", title: "Black Crappie", category: "Fish" },
  { id: "yellow-perch", name: "Perca flavescens", title: "Yellow Perch", category: "Fish" },
  { id: "common-carp", name: "Cyprinus carpio", title: "Common Carp", category: "Fish" },
  { id: "bowfin", name: "Amia calva", title: "Bowfin", category: "Fish" },
  { id: "honey-bee", name: "Apis mellifera", title: "Western Honey Bee", category: "Insects & pollinators" },
  { id: "eastern-bumble-bee", name: "Bombus impatiens", title: "Common Eastern Bumble Bee", category: "Insects & pollinators" },
  { id: "rusty-patched-bumble-bee", name: "Bombus affinis", title: "Rusty Patched Bumble Bee", category: "Insects & pollinators" },
  { id: "luna-moth", name: "Actias luna", title: "Luna Moth", category: "Insects & pollinators" },
  { id: "atlas-moth", name: "Attacus atlas", title: "Atlas Moth", category: "Insects & pollinators" },
  { id: "cecropia-moth", name: "Hyalophora cecropia", title: "Cecropia Moth", category: "Insects & pollinators" },
  { id: "hummingbird-hawk-moth", name: "Macroglossum stellatarum", title: "Hummingbird Hawk-Moth", category: "Insects & pollinators" },
  { id: "tiger-swallowtail", name: "Papilio glaucus", title: "Eastern Tiger Swallowtail", category: "Insects & pollinators" },
  { id: "blue-morpho", name: "Morpho peleides", title: "Blue Morpho", category: "Insects & pollinators" },
  { id: "green-darner", name: "Anax junius", title: "Common Green Darner", category: "Insects & pollinators" },
  { id: "twelve-spotted-skimmer", name: "Libellula pulchella", title: "Twelve-spotted Skimmer", category: "Insects & pollinators" },
  { id: "ebony-jewelwing", name: "Calopteryx maculata", title: "Ebony Jewelwing", category: "Insects & pollinators" },
  { id: "seven-spotted-ladybird", name: "Coccinella septempunctata", title: "Seven-spotted Lady Beetle", category: "Insects & pollinators" },
  { id: "common-firefly", name: "Photinus pyralis", title: "Common Eastern Firefly", category: "Insects & pollinators" },
  { id: "periodical-cicada", name: "Magicicada septendecim", title: "Periodical Cicada", category: "Insects & pollinators" },
  { id: "chinese-mantis", name: "Tenodera sinensis", title: "Chinese Mantis", category: "Insects & pollinators" },
  { id: "giant-water-bug", name: "Lethocerus americanus", title: "Giant Water Bug", category: "Insects & pollinators" },
  { id: "hercules-beetle", name: "Dynastes hercules", title: "Hercules Beetle", category: "Insects & pollinators" },
  { id: "goliath-beetle", name: "Goliathus goliatus", title: "Goliath Beetle", category: "Insects & pollinators" },
  { id: "european-stag-beetle", name: "Lucanus cervus", title: "European Stag Beetle", category: "Insects & pollinators" },
  { id: "tarantula-hawk", name: "Pepsis grossa", title: "Tarantula Hawk Wasp", category: "Insects & pollinators" },
  { id: "viceroy", name: "Limenitis archippus", title: "Viceroy Butterfly", category: "Insects & pollinators" },
  { id: "mourning-cloak", name: "Nymphalis antiopa", title: "Mourning Cloak", category: "Insects & pollinators" },
  { id: "red-admiral", name: "Vanessa atalanta", title: "Red Admiral", category: "Insects & pollinators" },
  { id: "raccoon", name: "Procyon lotor", title: "Raccoon", category: "Small mammals & primates" },
  { id: "striped-skunk", name: "Mephitis mephitis", title: "Striped Skunk", category: "Small mammals & primates" },
  { id: "virginia-opossum", name: "Didelphis virginiana", title: "Virginia Opossum", category: "Small mammals & primates" },
  { id: "porcupine", name: "Erethizon dorsatum", title: "North American Porcupine", category: "Small mammals & primates" },
  { id: "nine-banded-armadillo", name: "Dasypus novemcinctus", title: "Nine-banded Armadillo", category: "Small mammals & primates" },
  { id: "groundhog", name: "Marmota monax", title: "Groundhog", category: "Small mammals & primates" },
  { id: "black-tailed-prairie-dog", name: "Cynomys ludovicianus", title: "Black-tailed Prairie Dog", category: "Small mammals & primates" },
  { id: "american-red-squirrel", name: "Tamiasciurus hudsonicus", title: "American Red Squirrel", category: "Small mammals & primates" },
  { id: "eastern-gray-squirrel", name: "Sciurus carolinensis", title: "Eastern Gray Squirrel", category: "Small mammals & primates" },
  { id: "northern-flying-squirrel", name: "Glaucomys sabrinus", title: "Northern Flying Squirrel", category: "Small mammals & primates" },
  { id: "least-weasel", name: "Mustela nivalis", title: "Least Weasel", category: "Small mammals & primates" },
  { id: "ermine", name: "Mustela erminea", title: "Ermine", category: "Small mammals & primates" },
  { id: "muskrat", name: "Ondatra zibethicus", title: "Muskrat", category: "Small mammals & primates" },
  { id: "ringtail", name: "Bassariscus astutus", title: "Ringtail", category: "Small mammals & primates" },
  { id: "kinkajou", name: "Potos flavus", title: "Kinkajou", category: "Small mammals & primates" },
  { id: "white-nosed-coati", name: "Nasua narica", title: "White-nosed Coati", category: "Small mammals & primates" },
  { id: "white-faced-capuchin", name: "Cebus imitator", title: "Panamanian White-faced Capuchin", category: "Small mammals & primates" },
  { id: "mantled-howler", name: "Alouatta palliata", title: "Mantled Howler Monkey", category: "Small mammals & primates" },
  { id: "philippine-tarsier", name: "Carlito syrichta", title: "Philippine Tarsier", category: "Small mammals & primates" },
  { id: "sunda-slow-loris", name: "Nycticebus coucang", title: "Sunda Slow Loris", category: "Small mammals & primates" },
  { id: "rhesus-macaque", name: "Macaca mulatta", title: "Rhesus Macaque", category: "Small mammals & primates" },
  { id: "hamadryas-baboon", name: "Papio hamadryas", title: "Hamadryas Baboon", category: "Small mammals & primates" },
  { id: "little-brown-bat", name: "Myotis lucifugus", title: "Little Brown Bat", category: "Small mammals & primates" },
  { id: "large-flying-fox", name: "Pteropus vampyrus", title: "Large Flying Fox", category: "Small mammals & primates" },
  { id: "common-vampire-bat", name: "Desmodus rotundus", title: "Common Vampire Bat", category: "Small mammals & primates" },
  { id: "bottlenose-dolphin", name: "Tursiops truncatus", title: "Common Bottlenose Dolphin", category: "Ocean giants" },
  { id: "spinner-dolphin", name: "Stenella longirostris", title: "Spinner Dolphin", category: "Ocean giants" },
  { id: "pacific-white-sided-dolphin", name: "Lagenorhynchus obliquidens", title: "Pacific White-sided Dolphin", category: "Ocean giants" },
  { id: "common-dolphin", name: "Delphinus delphis", title: "Common Dolphin", category: "Ocean giants" },
  { id: "rissos-dolphin", name: "Grampus griseus", title: "Risso's Dolphin", category: "Ocean giants" },
  { id: "dalls-porpoise", name: "Phocoenoides dalli", title: "Dall's Porpoise", category: "Ocean giants" },
  { id: "harbor-porpoise", name: "Phocoena phocoena", title: "Harbor Porpoise", category: "Ocean giants" },
  { id: "long-finned-pilot-whale", name: "Globicephala melas", title: "Long-finned Pilot Whale", category: "Ocean giants" },
  { id: "false-killer-whale", name: "Pseudorca crassidens", title: "False Killer Whale", category: "Ocean giants" },
  { id: "minke-whale", name: "Balaenoptera acutorostrata", title: "Minke Whale", category: "Ocean giants" },
  { id: "sei-whale", name: "Balaenoptera borealis", title: "Sei Whale", category: "Ocean giants" },
  { id: "gray-seal", name: "Halichoerus grypus", title: "Gray Seal", category: "Ocean giants" },
  { id: "harbor-seal", name: "Phoca vitulina", title: "Harbor Seal", category: "Ocean giants" },
  { id: "northern-elephant-seal", name: "Mirounga angustirostris", title: "Northern Elephant Seal", category: "Ocean giants" },
  { id: "southern-elephant-seal", name: "Mirounga leonina", title: "Southern Elephant Seal", category: "Ocean giants" },
  { id: "hawaiian-monk-seal", name: "Neomonachus schauinslandi", title: "Hawaiian Monk Seal", category: "Ocean giants" },
  { id: "ribbon-seal", name: "Histriophoca fasciata", title: "Ribbon Seal", category: "Ocean giants" },
  { id: "galapagos-fur-seal", name: "Arctocephalus galapagoensis", title: "Galapagos Fur Seal", category: "Ocean giants" },
  { id: "steller-sea-lion", name: "Eumetopias jubatus", title: "Steller Sea Lion", category: "Ocean giants" },
  { id: "california-sea-lion", name: "Zalophus californianus", title: "California Sea Lion", category: "Ocean giants" },
  { id: "west-indian-manatee", name: "Trichechus manatus", title: "West Indian Manatee", category: "Ocean giants" },
  { id: "dugong", name: "Dugong dugon", title: "Dugong", category: "Ocean giants" },
  { id: "nilgai", name: "Boselaphus tragocamelus", title: "Nilgai", category: "Asia" },
  { id: "blackbuck", name: "Antilope cervicapra", title: "Blackbuck", category: "Asia" },
  { id: "chital", name: "Axis axis", title: "Chital", category: "Asia" },
  { id: "sambar", name: "Rusa unicolor", title: "Sambar", category: "Asia" },
  { id: "sika-deer", name: "Cervus nippon", title: "Sika Deer", category: "Asia" },
  { id: "takin", name: "Budorcas taxicolor", title: "Takin", category: "Asia" },
  { id: "himalayan-musk-deer", name: "Moschus chrysogaster", title: "Himalayan Musk Deer", category: "Asia" },
  { id: "kiang", name: "Equus kiang", title: "Kiang", category: "Asia" },
  { id: "onager", name: "Equus hemionus", title: "Onager", category: "Asia" },
  { id: "malayan-tapir", name: "Tapirus indicus", title: "Malayan Tapir", category: "Asia" },
  { id: "gerenuk", name: "Litocranius walleri", title: "Gerenuk", category: "Africa" },
  { id: "waterbuck", name: "Kobus ellipsiprymnus", title: "Waterbuck", category: "Africa" },
  { id: "lechwe", name: "Kobus leche", title: "Lechwe", category: "Africa" },
  { id: "addax", name: "Addax nasomaculatus", title: "Addax", category: "Africa" },
  { id: "scimitar-horned-oryx", name: "Oryx dammah", title: "Scimitar-horned Oryx", category: "Africa" },
  { id: "barbary-sheep", name: "Ammotragus lervia", title: "Barbary Sheep", category: "Africa" },
  { id: "bongo", name: "Tragelaphus eurycerus", title: "Bongo", category: "Africa" },
  { id: "bushbuck", name: "Tragelaphus scriptus", title: "Bushbuck", category: "Africa" },
  { id: "giant-forest-hog", name: "Hylochoerus meinertzhageni", title: "Giant Forest Hog", category: "Africa" },
  { id: "pygmy-hippo", name: "Choeropsis liberiensis", title: "Pygmy Hippopotamus", category: "Africa" },
  { id: "iberian-ibex", name: "Capra pyrenaica", title: "Iberian Ibex", category: "Europe" },
  { id: "alpine-marmot", name: "Marmota marmota", title: "Alpine Marmot", category: "Europe" },
  { id: "southern-pudu", name: "Pudu puda", title: "Southern Pudu", category: "South & Central America" },
  { id: "collared-peccary", name: "Dicotyles tajacu", title: "Collared Peccary", category: "South & Central America" },
  { id: "woolly-mammoth", name: "Mammuthus primigenius", title: "Woolly Mammoth (museum records)", category: "Historical" },
  { id: "aurochs", name: "Bos primigenius", title: "Aurochs (museum records)", category: "Historical" },
  { id: "cave-bear", name: "Ursus spelaeus", title: "Cave Bear (museum records)", category: "Historical" },
  { id: "irish-elk", name: "Megaloceros giganteus", title: "Irish Elk (museum records)", category: "Historical" },
  { id: "giant-moa", name: "Dinornis novaezealandiae", title: "North Island Giant Moa (museum records)", category: "Historical" },
  { id: "elephant-bird", name: "Aepyornis maximus", title: "Elephant Bird (museum records)", category: "Historical" },
  { id: "labrador-duck", name: "Camptorhynchus labradorius", title: "Labrador Duck (museum records)", category: "Historical" },
  { id: "xerces-blue", name: "Glaucopsyche xerces", title: "Xerces Blue Butterfly (museum records)", category: "Historical" },
  { id: "baiji", name: "Lipotes vexillifer", title: "Baiji (museum records)", category: "Historical" },
  { id: "falkland-wolf", name: "Dusicyon australis", title: "Falkland Islands Wolf (museum records)", category: "Historical" },
]

const NEO = [
  { id: 'vegetation', dataset: 'MOD_NDVI_M', title: 'Vegetation (NDVI)', category: 'Habitat', caption: 'Vegetation index · NASA MODIS, monthly' },
  { id: 'leaf-area', dataset: 'MOD15A2_M_LAI', title: 'Leaf area index', category: 'Habitat', caption: 'Leaf area index · NASA MODIS, monthly' },
  { id: 'productivity', dataset: 'MOD17A2_M_PSN', title: 'Plant productivity', category: 'Habitat', caption: 'Net primary productivity · NASA MODIS, monthly' },
  { id: 'snow', dataset: 'MOD10C1_M_SNOW', title: 'Snow cover', category: 'Conditions', caption: 'Snow cover · NASA MODIS, monthly' },
  { id: 'fires', dataset: 'MOD14A1_M_FIRE', title: 'Active fires', category: 'Conditions', caption: 'Active fires · NASA MODIS, monthly' },
  { id: 'temperature', dataset: 'MOD_LSTD_M', title: 'Land surface temp', category: 'Conditions', caption: 'Daytime land surface temperature · NASA MODIS, monthly' },
  { id: 'rainfall', dataset: 'GPM_3IMERGM', title: 'Rainfall', category: 'Conditions', caption: 'Monthly rainfall · NASA GPM IMERG' },
  { id: 'cloud-fraction', dataset: 'MODAL2_M_CLD_FR', title: 'Cloud fraction', category: 'Conditions', caption: 'Cloud fraction · NASA MODIS, monthly' },
  { id: 'sst', dataset: 'MYD28M', title: 'Sea surface temp', category: 'Ocean', caption: 'Sea surface temperature · NASA MODIS Aqua, monthly' },
  { id: 'chlorophyll', dataset: 'MY1DMM_CHLORA', title: 'Ocean chlorophyll', category: 'Ocean', caption: 'Chlorophyll concentration · NASA MODIS Aqua, monthly' },
]

const STAMP = new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' })

const fetchBuf = async (url) => {
  const res = await fetch(url, { headers: { 'User-Agent': 'waypoints-site-build' } })
  if (!res.ok) throw new Error(`${res.status} ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

const SKIP_EXISTING = process.argv.includes('--skip-existing')

async function speciesLayer({ id, name, title, category }) {
  const match = await (await fetch(`https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}`)).json()
  const key = match.usageKey
  if (!key) throw new Error(`GBIF match failed for ${name}`)

  // Incremental mode: texture already on disk — refresh the registry row only.
  const file0 = `layer-${id}.png`
  if (SKIP_EXISTING && fs.existsSync(path.join(dest, file0))) {
    return {
      id, title, category,
      kind: 'overlay',
      texture: `textures/${file0}`,
      opacity: 1,
      caption: `${title} — all-time occurrence records · GBIF · pulled ${STAMP} · ${match.scientificName}`,
      freshness: `GBIF · ${STAMP.toUpperCase()}`,
      source: 'GBIF',
    }
  }

  const Z = 1, COLS = 4, ROWS = 2, T = 1024
  const tiles = await Promise.all(
    Array.from({ length: COLS * ROWS }, (_, i) => {
      const x = i % COLS, y = Math.floor(i / COLS)
      const url = `https://api.gbif.org/v2/map/occurrence/density/${Z}/${x}/${y}@2x.png?srs=EPSG%3A4326&taxonKey=${key}&style=classic.point`
      return fetchBuf(url).then((buf) => ({ x, y, buf })).catch(() => null)
    }),
  )
  const composite = tiles.filter((t) => t && t.buf.length > 0)
    .map(({ x, y, buf }) => ({ input: buf, left: x * T, top: y * T }))
  if (!composite.length) throw new Error(`no data tiles for ${name}`)
  const file = `layer-${id}.png`
  await sharp({ create: { width: COLS * T, height: ROWS * T, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite(composite)
    .png()
    .toFile(path.join(dest, file))
  console.log(`✓ ${title} (${match.scientificName}, taxonKey ${key})`)
  return {
    id, title, category,
    kind: 'overlay',
    texture: `textures/${file}`,
    opacity: 1,
    caption: `${title} — all-time occurrence records · GBIF · pulled ${STAMP} · ${match.scientificName}`,
    freshness: `GBIF · ${STAMP.toUpperCase()}`,
    source: 'GBIF',
  }
}

async function neoLayer({ id, dataset, title, category, caption }) {
  const now = new Date()
  for (let back = 1; back <= 8; back++) {
    const d = new Date(now.getFullYear(), now.getMonth() - back, 1)
    const stamp = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
    const url = `https://neo.gsfc.nasa.gov/archive/rgb/${dataset}/${dataset}_${stamp}.PNG`
    try {
      const buf = await fetchBuf(url)
      const file = `layer-${id}.png`
      await sharp(buf).resize(3600, 1800, { fit: 'fill' }).png().toFile(path.join(dest, file))
      console.log(`✓ ${title} (NEO ${dataset}, ${stamp})`)
      return {
        id, title, category,
        kind: 'overlay',
        texture: `textures/${file}`,
        opacity: id === 'vegetation' ? 0.85 : 0.9,
        caption: `${caption} (${stamp}) · via NASA Earth Observations`,
        freshness: `NASA · ${stamp}`,
        source: 'NASA',
      }
    } catch { /* month not published — walk back */ }
  }
  throw new Error(`no NEO data found for ${dataset}`)
}

// Batched: max 6 concurrent jobs so GBIF/NEO see a polite client.
const jobs = [...SPECIES.map((sp) => () => speciesLayer(sp)), ...NEO.map((n) => () => neoLayer(n))]
const layers = []
for (let i = 0; i < jobs.length; i += 6) {
  const results = await Promise.allSettled(jobs.slice(i, i + 6).map((j) => j()))
  for (const r of results) {
    if (r.status === 'fulfilled') layers.push(r.value)
    else console.error('✗', r.reason.message)
  }
  console.log(`— batch done (${Math.min(i + 6, jobs.length)}/${jobs.length})`)
}
// Keep the drawer tidy: stable category order, alphabetical within.
const CAT_ORDER = ['Big game', 'Waterfowl', 'Upland birds', 'Raptors', 'Fish', 'Furbearers & small game', 'Reptiles & amphibians', 'Birds & icons', 'Bears of the world', 'Africa', 'Asia', 'Europe', 'South & Central America', 'Australia & Oceania', 'Arctic & Antarctic', 'Ocean giants', 'Long-distance birds', 'Songbirds', 'Waterbirds & shorebirds', 'Saltwater', 'Insects & pollinators', 'Small mammals & primates', 'Historical', 'Habitat', 'Conditions', 'Ocean']
layers.sort((a, b) => (CAT_ORDER.indexOf(a.category) - CAT_ORDER.indexOf(b.category)) || a.title.localeCompare(b.title))
fs.writeFileSync(path.join(root, 'src', 'data', 'layers.json'), JSON.stringify(layers, null, 2))
console.log(`layers.json: ${layers.length} layers registered`)
